[Variables]
Color1=255,255,255,250
Color2=255,255,255,200
Color3=255,255,255,153
Color4=186,55,51,200
Angle20=-0.35
LocalFontFace=ITC Avant Garde Pro XLt
LocalFontFace2=ITC Avant Garde Pro Md


January=jan
February=feb
March=mar
April=apr
May=may
June=jun
July=jul
August=aug
September=sep
October=oct
November=nov
December=dec

Monday=mon
Tuesday=tue
Wednesday=wed
Thursday=thu
Friday=fri
Saturday=sat
Sunday=sun

