
[normalwc]
StringAlign=Center
StringCase=None
StringStyle=Normal
StringEffect=Shadow
FontEffectColor=0,0,0,50
FontColor=255,255,255,170
FontFace=#LocalFontFace#
AntiAlias=1
ClipString=0

[boldwr]
StringAlign=right
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,50
FontColor=255,255,255,170
FontFace=#LocalFontFace2#
AntiAlias=1
ClipString=0

[boldplayer]
StringAlign=right
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,50
FontColor=255,255,255,220
FontFace=#LocalFontFace2#
AntiAlias=1
ClipString=1

[boldtime]
StringAlign=left
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,100
FontColor=255,255,255,220
FontFace=#LocalFontFace2#
AntiAlias=1
ClipString=0

[playerbuttons]
StringAlign=left
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,50
FontColor=255,255,255,220
FontFace=Webdings
FontSize=11
AntiAlias=1
ClipString=0



