[Variables]

;==============================================================
;			==WEATHER CONFIGS==
;==============================================================
;Please replace your location code for Weather.com below
;==============================================================
;Set "Metric=" to m for metric(ºC) measures or f(ºF) for non-metric
;==============================================================
;You can give an alias to you city using the "CityAlias", leave it
;blank for the default name.
;==============================================================

Location=INXX0100
Metric=m
CityAlias=Patna, Bihar



;==============================================================
;			==NOW PLAYING CONFIGS==
;==============================================================
;you can see if your player is supported here: 
;http://docs.rainmeter.net/manual/plugins/nowplaying
;==============================================================
;"DisablePlayPause": if you want to disable te feature that let 
;you pause/play your musicby just clicking in the music applet.
;(1 = disable; 0 = enable) 
;==============================================================

Player=CAD
DisablePlayPause=0

;==============================================================
;			==GMAIL USER==
;==============================================================
;Do not put the domain (@gmail.com)
;==============================================================
;Use "HideCalendar" as 1 to hide the date (0 to show)
;==============================================================

User='shashank7200'
Password='Sureshprasad@7200'
messageinterval=45
HideCalendar=0



;==============================================================
;			==HARD DISKS CONFIGS==
;==============================================================

Drive1=C
Drive2=D



;==============================================================
;			==SLIDESHOW FOLDER==
;==============================================================

IMGFolder='C:\Users\AshwaMegh\Pictures\Wallpaper'
PreserveRatio=2

;==============================================================
;			==Color==
;==============================================================

ClockColor=00a8ed
WeatherColor=00a8ed
GmailColor=25bfb5
SystemColor=f54949
NotesColor=25bfb5
UserColor=27343d
SearchColor=f54949
BinColor=00a8ed
