[Variables]

;Large Launcher Buttons====================

LLT1=Chrome
;Program Name
LLP1=C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
;Program Path
LLI1=C:\Users\AshwaMegh\Pictures\MY ICon Pack\Marcus-Roberto-Google-Play-Google-Chrome.ico
;Program Icon

LLT2=Android Studio
LLP2=C:\Program Files\Android\Android Studio\bin\studio64.exe
LLI2=C:\Users\AshwaMegh\Pictures\MY ICon Pack\JPGs\Android_Studio_icon.svg.png

LLT3=Github
LLP3=C:\Users\AshwaMegh\AppData\Local\Apps\2.0\9C75JE7X.ECH\8PK3BA7A.GY0\gith..tion_317444273a93ac29_0003.0002_34b4671ab86a4854\GitHub.exe
LLI3=C:\Users\AshwaMegh\Pictures\MY ICon Pack\JPGs\39062.png

LLT4=Atom
LLP4=C:\Users\AshwaMegh\AppData\Local\atom\Update.exe
LLI4=C:\Users\AshwaMegh\Pictures\MY ICon Pack\JPGs\Bokehlicia-Captiva-Atom.ico

LLT5=CyberGhost
LLP5=C:\Program Files\CyberGhost 6\CyberGhost.exe
LLI5=C:\Users\AshwaMegh\Pictures\MY ICon Pack\JPGs\icon_cg_windows.png

LLT6=Firefox
LLP6=C:\Program Files\Mozilla Firefox\firefox.exe
LLI6=C:\Users\AshwaMegh\Pictures\MY ICon Pack\JPGs\firefox-512.png

;Small Launcher Buttons===========================

SLT1=Photshop
SLP1=C:\Program Files\Adobe\Adobe Photoshop CS5.1 (64 Bit)\Photoshop.exe
SLI1=C:\Users\AshwaMegh\Pictures\MY ICon Pack\JPGs\Photoshop_CC_icon.png

SLT2=Illustrator
SLP2=C:\Program Files (x86)\Adobe\Adobe Illustrator CS5.1\Support Files\Contents\Windows\Illustrator.exe
SLI2=C:\Users\AshwaMegh\Pictures\MY ICon Pack\JPGs\Adobe_Illustrator_Icon_CS6.png

SLT3=Premiere Pro
SLP3=C:\Program Files\Adobe\Adobe Premiere Pro CS5.5\Adobe Premiere Pro.exe
SLI3=C:\Users\AshwaMegh\Pictures\MY ICon Pack\JPGs\Adobe_Premiere_Pro_CS6_Icon.png

SLT4=After Effects
SLP4=C:\Program Files\Adobe\Adobe After Effects CS5.5\Support Files\AfterFX.exe
SLI4=C:\Users\AshwaMegh\Pictures\MY ICon Pack\JPGs\Adobe_After_Effects_CS6_Icon.png

SLT5=Audition
SLP5=C:\Program Files (x86)\Adobe\Adobe Audition CS5.5\Adobe Audition.exe
SLI5=C:\Users\AshwaMegh\Pictures\MY ICon Pack\JPGs\Adobe_Audition_CC_Logo.png

SLT6=MediaEncoder
SLP6=C:\Program Files\Adobe\Adobe Media Encoder CS5.5\Adobe Media Encoder.exe
SLI6=C:\Users\AshwaMegh\Pictures\MY ICon Pack\JPGs\OLeppsS.png

;Folder Launcher BUttons=========================

FLP1=C:\Users\AshwaMegh\Downloads
;Folder Path
FLN1=Downloads
;Folder Name

FLP2=C:\Desktop
FLN2=Desktop

FLP3=C:\Users\AshwaMegh\Music
FLN3=Music

FLP4=C:\Program Files\Rainmeter
FLN4=Rainmeter

FLP5=C:\Users\AshwaMegh\Videos
FLN5=Videos

FLP6=C:\Users\AshwaMegh\Pictures
FLN6=Pictures

FLP7=C:\Users\AshwaMegh\Documents
FLN7=Documents

;Clock Webpages==============================

WN1=Facebook
;Webpage Name
WA1=https:\\facebook.com
;Webpage Address

WN2=Udacity
WA2=https://classroom.udacity.com/me

WN3=YouTube
WA3=http:\\youtube.com

WN4=Github
WA4=https://github.com/shashank7200

WN5=CodeWars
WA5=https://www.codewars.com/join

WN6=Mail
WA6=http:\\mail.google.com

;Misc======================

player=WMP
Drive=C:


